### ISSUE TITLE
Add region-specific logos to website Homepage hero

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1054]
Hey Nata :) 

What we want to do is basically change the logos each user see depending on the region they are at. 

So if they enter from APAC you see the ones on the APAC list and if you enter from any country included on EMEA you see the ones that are on the EMEA list.

ALSO, all americas go together (we don't have that much customers from LATAM)

**I'll let you know when the list is ready**

And I will create you the mockups and anything you need for this change.

cc @skcopland 

List:
https://docs.google.com/spreadsheets/d/1NWaNglWtunjVSVV4ebouKR_vJw41Df7v/edit#gid=414328728

**Comment by natapg** [comment]
Created logic to display logos by region. 
https://github.com/fingerprintjs/fingerprint.com/pull/1081/files
Work will continue when the mockups are ready.

**Comment by sabrinazimet** [comment]
Ready! https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?node-id=1154%3A16372&t=GZ0MrJ83VFy9p6ZJ-1
