### ISSUE TITLE
Add new pictures to Careers Page

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1088]
Hi Nata :) !  

I left a couple of new offsite images for you to add for the careers page whenever you can. [HERE ](https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?node-id=923%3A13416&t=Y8vNerLCW2ntAhAl-1)

I also selected some of the old ones for you to delete, because 1) I think we have too many now and 2) Some of the people who appear doesn't work for the company anymore. 

Thank you

**Comment by sabrinazimet** [comment]
cc @skcopland

**Comment by natapg** [comment]
thanks Sabri, I'll update it today :)
