### ISSUE TITLE
Add Java SDK on SDKs and Libraries

### ISSUE THREAD

**Issue by Orkuncakilkaya** [fingerprintjs/fingerprint.com#1105]
Hey all, 👋 
We have released our Java SDK 🎉 

Could we add this to SDKs and Libraries page?

Repo URL: https://github.com/fingerprintjs/fingerprint-pro-server-api-java-sdk

Docs page will be published soon, I'll update here once it's published

**Comment by natapg** [comment]
@Orkuncakilkaya do we have the documentation ready?

**Comment by Orkuncakilkaya** [comment]
@natapg Here is our document for Java SDK
https://dev.fingerprint.com/docs/java-server-api-sdk

**Comment by natapg** [comment]
thanks @Orkuncakilkaya !
@sabrinazimet can we create a cover image for this new card :) ?
https://worldvectorlogo.com/logo/java

**Comment by sabrinazimet** [comment]
Hi @natapg here https://www.figma.com/file/niHrIRowTbqQhDO7W5CPNf/Website-Old?node-id=6384%3A49141&t=k4R1pL4qtAuz4seT-1
![Integration Card](https://user-images.githubusercontent.com/111449971/222185345-885833ae-bb18-49e8-a2fd-6c665d0c19be.png)

background: #3174B9 5% opacity.

Thank you!

**Comment by natapg** [comment]
done! @Orkuncakilkaya 
Thanks @sabrinazimet for your help!
