### ISSUE TITLE
Get a Demo CTA

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1170]
https://www.notion.so/fingerprintjs/fd2bf2b2e85a49d6a4e93d246191e54e?v=548bf24b90ff4db8881c750b5e4cc2f6&p=0c01530d097c469d8b31e07d7906ede1&pm=s

Hi Nata, mockups are ready for you to start.

I left you some guiding comments on Figma https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?node-id=1276%3A30777&t=HUK9LvFY8NS4kDp9-1

Thank you so very much.

**Comment by sabrinazimet** [comment]
(please leave the botd one for the end)

**Comment by natapg** [comment]
Hi Sabri :) thanks! I'll let you know when it's ready
