### ISSUE TITLE
Update g2 Badges on website

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1213]
Hey, we've received new 2023 G2 badges! Can we update them?

Mockup:
https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?node-id=1468%3A62081&t=Hjl5u9o8N9BQjp3L-1

Thank you so much.

**Comment by dcorso21** [comment]
fastest implementation indeed! 🏎️💨

**Comment by sabrinazimet** [comment]
🏎️💨💨!!!
