### ISSUE TITLE
Include Github Stars on Developer dropdown 

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1215]
Hi Nata :) we are going to include the Github stars on the Developer DP.

Is there a way for us to have the number automatically updated? Or we have to update it every time it increases importantly?

Thanks! 

Mockups: https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?node-id=1693%3A40719&t=QPtBWN7XKdvlmaGG-1

**Comment by natapg** [comment]
Hi 👩🏻‍🚀 , the number of stars is updated automatically :)

**Comment by natapg** [comment]
done, please check @sabrinazimet !
https://fingerprint-com-git-fix-add-github-stars-to-topnav-fp-pro.vercel.app/
