### ISSUE TITLE
Fix detail on new quote section

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1247]
<img width="1035" alt="Captura de Pantalla 2023-04-18 a la(s) 22 29 59" src="https://user-images.githubusercontent.com/111449971/232943265-43e687d6-2f72-4260-9eea-f13062985f15.png">

Hi nata, can we do the logo size responsive in desktop so when the screen is smaller the size get a little bit smaller and this doesn't happen? thanks! 

it only happens with dropbox logo but we have to apply it to all of them I think (to be neat)

**Comment by natapg** [comment]
I don't think that making the logos smaller is the best solution, I would prefer to move to the mobile layout in a higher resolution. Let me take a look

**Comment by natapg** [comment]
check here @sabrinazimet 
https://fingerprint-com-git-fix-quotes-section-fp-pro.vercel.app/
it matches the layout change from the section above, so it looks good

**Comment by sabrinazimet** [comment]
this is great and better solution than the one I though 🧠 thank you!!!!!

**Comment by natapg** [comment]
you’re welcome :) please approve -> https://github.com/fingerprintjs/fingerprint.com/pull/1248
