### ISSUE TITLE
Sign Up Log In screens CONSISTENCY reviews

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1249]
Hi @natapg nice Wednesday  

1)  Minor change: I can't find on the mockups where this blue light color on the password placeholder is coming from, but can we change it to #F6F7FA, and please apply this to **ALL of this type of states all across the dashboard.** 

<img width="333" alt="Screen Shot 2023-04-19 at 11 58 33" src="https://user-images.githubusercontent.com/111449971/233116709-c853ce30-3eac-4ed5-a603-653590a0a794.png">

2) Can we make these last changes I created for Log in and Sign up screen?

I am sorry I gave you this task in out of phase moments, but I really didn't expect to see the inconsistencies I found between these two screens on mobile view.

So I made them both consistent now.

These are the final designs (same mockup I shared yesterday)
<img width="245" alt="Screen Shot 2023-04-19 at 12 04 29" src="https://user-images.githubusercontent.com/111449971/233118364-f419e10a-cb53-4b2c-91db-3c9d83318502.png">

Thanks :) !

**Comment by natapg** [comment]
Added fixes here -> https://dashboard-git-fix-sign-up-sign-in-inconsistencies-fp-pro.vercel.app/
Assigned to @ctizen

**Comment by sabrinazimet** [comment]
omg this looks stunning @natapg

**Comment by sabrinazimet** [comment]
🤩🤩🤩🤩🤩
