### ISSUE TITLE
Update Compliance section on HP

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1265]
Holis I updated with new compliance badge ISO 27001 this section and I will be updating Security Page soon

for this:
- Add ISO 27001 Badge
- Change SOC 2 Type 2 for SOC 2 Type II as the mockup
- Chnage corner radius of badges on mobile to 8px (it was wrong idk why I did them that way)

I used this mockup:
https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?node-id=2079%3A45402&t=lG3mVmtfJkRVebwo-1

**Comment by natapg** [comment]
holis, this will be done on the ticket https://github.com/fingerprintjs/fingerprint.com/issues/1266

**Comment by sabrinazimet** [comment]
THANKS
