### ISSUE TITLE
Update security webpage 

### ISSUE THREAD

**Issue by priyankasinha13** [fingerprintjs/fingerprint.com#1266]
Please use this document to update the security page since we have to add the ISO certification 
https://docs.google.com/document/d/1XTTR7S7vPWelkdfTZcu4vgJ_3jfRYIBgSrVUwQAq07g/edit

**Comment by natapg** [comment]
the document and the mockup are not synchronized, please check
-> https://github.com/fingerprintjs/fingerprint.com/issues/1271

**Comment by natapg** [comment]
I'll leave this on standby until I have a mockup and document that are aligned
cc @sabrinazimet

**Comment by sabrinazimet** [comment]
ok now they are supposed to be aligned (or at least mockups are with the VERIFIED 100% VERSIOn of copy and orders)
