### ISSUE TITLE
Update Careers Page (style and sections)

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1292]
Hi Nata.

This page is supposed to be launched on production **at the same time that About Page is launched.** 
About Page is _about_ to be ready lol, but I am still waiting for some last spell edits. (hope that happens early next week)

Anyways, I think you can already start with this project (Careers Page). We can leave everything prepared and ready for the moment About Page is ready too, so we can make both live at the same time :)

Let me know if that works

Mockup: https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?type=design&node-id=2431%3A42640&t=MHIkGVXVtpkpPtfX-1

For the map, you can add the effect Gabe suggested!

Thank you!

**Comment by natapg** [comment]
first DP : https://fingerprint-com-git-feat-careers-page-update-fp-pro.vercel.app/careers/

**Comment by sabrinazimet** [comment]
looks beautiful!
