### ISSUE TITLE
About Page (New) 

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1296]
https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?type=design&node-id=1139%3A15700&t=4wsFAn38kxsYEylL-1

HI! ABOUT PAGE is almost readyyyy, but I think you can start! 

The only pending changes rn are copy: 
1) HERO subheading copy (Courtney is going to change it) 
2) ModernCTO CTA copy (I think this will be only a copy change)

Thank you.

 I will move to "ready for development" when 100% finalized but I know you like to have this tasks created as soon as possible so here it is :) sdub

**Comment by natapg** [comment]
The first sections are ready to review !! -> https://fingerprint-com-git-feat-about-us-page-fp-pro.vercel.app/about-us/

**Comment by sabrinazimet** [comment]
It is looking amazing! We need to know the position of this page on the Nav. I re-asked Courtney, I'll let you know as soon as possible and create Mockup

**Comment by sabrinazimet** [comment]
https://www.figma.com/file/mOlOAQbh5YeoamcKM15Mif/Web-Design-System---2022?type=design&node-id=484%3A4507&t=wCiYSKK2AWLP0Cp7-1 header and footer

**Comment by sabrinazimet** [comment]
looks great, the animation is not what I expected, but the idea is there! the only thing is that **the filling with orange** should be run/activated by the **scrolling** of the user, not automatically.

If the user scrolls only up to certain part, the filling should stop and wait until scrolling is reactivated.

**Comment by natapg** [comment]
updateddd
https://fingerprint-com-git-about-timeline-section-fp-pro.vercel.app/about-us/
something like this? t

**Comment by sabrinazimet** [comment]
more like what GitHub does on their landing page:

https://github.com/fingerprintjs/fingerprint.com/assets/111449971/75193596-5cbf-440c-a7a0-ed00de742e02

**Comment by natapg** [comment]
got it, I can reverse it when it scrolls up

**Comment by sabrinazimet** [comment]
you can doeverything!! thanks

**Comment by natapg** [comment]
updated!

**Comment by sabrinazimet** [comment]
thanks, looks good! fixed scrolling should be activated when **whole section** arrives to viewpoint.
when you scroll down, no matter if the mouse is hovering the timeline or not, the scrolling effect must be activated and when the timeline is in end state it can unlock and you can go to next section.

**Comment by sabrinazimet** [comment]
https://github.com/fingerprintjs/fingerprint.com/assets/111449971/a85b5325-88ee-4e2a-b064-1551312282c5

I mean that this should be fixed no matter if you are hovering the timeline or not

**Comment by natapg** [comment]
thanks, I'll let you know when it's ready.

**Comment by natapg** [comment]
done! I'll assign the PR to @dcorso21

**Comment by sabrinazimet** [comment]
so how is it looking? as the first version like this? https://app.asana.com/0/1204342528033400/1204629197689233/f

**Comment by natapg** [comment]
I added back the fixed scrolling, but this time taking another approach. If this does not work we will have to change the design of the page

**Comment by natapg** [comment]
reworked timing of animations

**Comment by sabrinazimet** [comment]
the animation looks so good! the only thing i notice is this blur on the background of certified that makes it a little less readable. we can talk about it tomomrrow so i express myself better. but it is just a tiny detail

![Uploading Screen Shot 2023-05-22 at 01.25.52.png…]()

**Comment by natapg** [comment]
I can't see the image, but I think I know what you mean and I think I sdub it. Let's talk about this during the day

**Comment by sabrinazimet** [comment]
looks amazing!!!!!!!!!!!!!!!!!!!!!!!!
