### ISSUE TITLE
Improve demo page

### ISSUE THREAD

**Issue by natapg** [fingerprintjs/fingerprint.com#1332]
Hi @sabrinazimet . We want to do some improvements to the demo sdubpage. 
1 We need to add an error status when we have the visitorId but not the visit history
eg.
![image](https://github.com/fingerprintjs/fingerprint.com/assets/47128448/ab9e7954-03c7-4984-b5c6-d7e3b45af0b7)
2 We need to improve the loading state visually separating the page loading state from the fingerprinting loading state making it clear that the two processes are distinct.

Let's discuss these details in a call when we have time to work on this tkmnat

**Comment by sabrinazimet** [comment]
hi sdub thank you :) 



1: in these screenshots i am pointing 2 different areas, do you want the **error state** on the section A or B? or both? 
<img width="551" alt="Screen Shot 2023-05-26 at 13 28 56" src="https://github.com/fingerprintjs/fingerprint.com/assets/111449971/b5547eab-c58d-4c94-8712-b7b3be5fed93">
<img width="1348" alt="Screen Shot 2023-05-26 at 13 28 45" src="https://github.com/fingerprintjs/fingerprint.com/assets/111449971/4a46800b-d7db-4cb2-b924-9af693f5651b">

2: we can talk about that when you come back tkmsas, I am not very clear on what we need
3: doesn't it make sense to wait until we launch smart signals? we may probably change the demo there too


thanks!!!!!!!!

**Comment by natapg** [comment]
the section B on hp and demo page! but don't sdub, we will discuss it later, this ticket is to not forget this task
