### ISSUE TITLE
Identification Page

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1333]
Hi! 

Context: 
We are dividing FP Pro page into two:
1) identification page 
2) platform page

**Identification Page is ready to develop.** 

Figma: https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?type=design&node-id=2941%3A70725&t=1HFqdSbYCEU4Vvai-1

We mostly did copy changes, here the doc, but I already updated the mockup https://docs.google.com/document/d/1jP7wlxYC1jrO0VQqr-zA66XE2uLv0XKYsV_TNlXSdVU/edit#

_Note: if you find "visitorID" all together, please update to visitor ID separate. We could have missed it. Applicable to all pages I am going to create you tickets for._ 

THANK YOU!

**Comment by natapg** [comment]
First version -> https://fingerprint-com-git-feat-integrations-page-fp-pro.vercel.app/products/identification/ !!
missing:
metadata title and description
update header / footer

**Comment by sabrinazimet** [comment]
maybe this is because of Vercel but code snippet doesn't wrk properly 
<img width="686" alt="Screen Shot 2023-05-30 at 22 41 06" src="https://github.com/fingerprintjs/fingerprint.com/assets/111449971/ccfdba66-c557-4936-af29-3d37f45fab5b">

**Comment by sabrinazimet** [comment]
meta data and url are on the doc

**Comment by natapg** [comment]
code snippet should work now, and the metadata has already been updated today with the information provided by Louise. Thank you! The only thing missing is the location in the header/footer
