### ISSUE TITLE
Platform Page

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1349]
Hi again, this is the other part that come off from old Fingerprint Pro Page:

Context:
We are dividing FP Pro page into two:

1) identification page ✅
**2) platform page** 

Now Platform Page is ready to develop too

Figma:
https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?type=design&node-id=3128%3A63220&t=q1bVOfpKu9UBcCki-1

Doc:
https://docs.google.com/document/d/11vqrDa5jMsFoCKV623YHGH9MQTJRVjayTs7sebvzyXY/edit#heading=h.2830jlz45o5u

Note: if you find "visitorID" all together, please update to visitor ID separate. We could have missed it. Applicable to all pages I am going to create you tickets for.

THANK YOU!

**Comment by sabrinazimet** [comment]
URL: https://fingerprint.com/products/fingerprint-pro/
Meta title: Device intelligence for web and mobile apps | Fingerprint
Meta description: Powered by the most accurate device identification technology, Fingerprint provides device intelligence for web and mobile applications.

**Comment by sabrinazimet** [comment]
meta data and url are on the doc

**Comment by sabrinazimet** [comment]
https://github.com/fingerprintjs/fingerprint.com/assets/111449971/4ea01177-0fb0-4f3a-bf7d-7ef8a24dbd98

this is a simple explanation of the animation for the hero. 

if this takes you too much time, let's use just a static image and then we can animate for second iteration

**Comment by natapg** [comment]
first version! -> https://fingerprint-com-git-smart-signals-platform-page-fp-pro.vercel.app/products/fingerprint-pro/
