### ISSUE TITLE
Pricing Page SS updates

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1352]
Hi, you've already seen this :)

mockup: https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?type=design&node-id=1295%3A24021&t=fjgQY1sGXvZXi5yl-1

I am not sure if FAQ content is going to change yet. I'll let you know.

**Comment by natapg** [comment]
I don't have access to the document, is there any change in the FAQ?

**Comment by sabrinazimet** [comment]
only a few

**Comment by natapg** [comment]
First version ready! https://fingerprint-com-git-pricing-smart-signals-fp-pro.vercel.app/pricing/
