### ISSUE TITLE
Update Bot detection Page style

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1395]
https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?type=design&node-id=3531%3A172827&t=DxJh0l8U10PJBCuF-1

mockup! (you have already seen it)

**Comment by natapg** [comment]
DP ! -> https://fingerprint-com-git-botd-last-sections-fp-pro.vercel.app/products/bot-detection/

**Comment by sabrinazimet** [comment]
Thanks! Looks greattttt!!!!!!! I left some comments on Figma.
