### ISSUE TITLE
Pricing Detailed features - dropdown preview

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1396]
Hi @natapg just like Amplitude does: 

https://github.com/fingerprintjs/fingerprint.com/assets/111449971/e3931f85-ec50-4476-ae20-12514f060c6d

we want to add some icons/words to indicate how complete the features are on each plan. 

<img width="630" alt="Screen Shot 2023-06-09 at 13 30 54" src="https://github.com/fingerprintjs/fingerprint.com/assets/111449971/211a4645-c803-49be-b484-0fdcceedc76f">

we need this to appear ONLY when the dropdown is closed. Again, as Amplitude.

mockup:
https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?type=design&node-id=3532%3A56296&t=DxJh0l8U10PJBCuF-1

doc: (I have a pending question there)
https://docs.google.com/spreadsheets/d/1EHXovjXeyMeLIUXkTuKGBLXpEabhzwa-3JLJROC3lSE/edit#gid=485111080

thanks!

**Comment by natapg** [comment]
Sorry for the delay! First version -> https://fingerprint-com-git-fix-add-empty-state-pricing-fp-pro.vercel.app/pricing/

**Comment by sabrinazimet** [comment]
Thanks, I'll share it with Louise because I still have a pending comment on
the doc, and I get back to you. It looks and works perfectly :)
