### ISSUE TITLE
Add a content block CTA for webinar on SS Page, Homepage and Bot detection page.

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1411]
Hi Nata!

We need to add this CTA section for a couple of days until the Webinar is out. It will live in 3 pages: 
- SS Page
- Homepage
- Bot detection Page

https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?type=design&node-id=3668%3A153797&t=avStx8WFw0cgf0rS-1

Thanks!

**Comment by natapg** [comment]
DP: https://fingerprint-com-git-fix-add-webinar-banner-fp-pro.vercel.app/

**Comment by sabrinazimet** [comment]
hi, it looks great, thank you! I left some details comments on Figma,
especially on mobile view, bust just a couple of very tiny things.
https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?type=design&node-id=3668%3A137203&t=rnEXjiToorcdRJtd-1

**Comment by natapg** [comment]
Thank you, I've updated to the current version of the mockup->
https://fingerprint-com-git-fix-add-webinar-banner-fp-pro.vercel.app/

**Comment by sabrinazimet** [comment]
LOOKS PERFECT. I'll send it for approval
