### ISSUE TITLE
Eliminate Bot detection button from Chip section

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1425]
this is a little odd for users, they seem not to be understanding that both things are clickable, so we are doing this change

follow the comment on this frame: 

https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?type=design&node-id=3897%3A97424&t=xWEfm2xMvNFmFn5H-1

**Comment by sabrinazimet** [comment]
I am not sure the hover effect is intuitive enough. probably we should put back the underline

**Comment by natapg** [comment]
done :)
