### ISSUE TITLE
Text changes on Webinar CTA

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1444]
Hi, :))))) would you please

Change date from "1:30PM EDT (5:30 PM UTC), JUNE 27 2023" to **"RECORDED WEBINAR"**
+
Change botton from "Save your Spot" to  **"Watch On-Demand Now"** 
?

Like this: 
![SSWebinarCTA03](https://github.com/fingerprintjs/fingerprint.com/assets/111449971/65972a2e-bf3c-426a-aba0-ff313c072026)

THANK YOU!

**Comment by sabrinazimet** [comment]
link https://www.youtube.com/watch?v=sf8KM8UgtYY

**Comment by natapg** [comment]
done :) !

**Comment by sabrinazimet** [comment]
hi, we need to change the link to https://try.fingerprint.com/smart-signals-webinar?utm_source=website&utm_medium=website&utm_campaign=smart-signals-launch-corp-marketing&utm_content=notification-bar

**Comment by natapg** [comment]
I think it's the same change that @fpjsmarketing requested earlier so I'll close the ticket
