### ISSUE TITLE
Footer changes

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1458]
Hi Nata, we changed a little bit the footer :) 

This are the new mockups. Let me know if you need anything!

https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?type=design&node-id=4190%3A54759&mode=design&t=B5bfAYiEFCe1JfmV-1

Thanks

**Comment by natapg** [comment]
Dp with the changes! I left a comment regarding a link -> https://fingerprint-com-git-fix-update-footer-fp-pro.vercel.app/
let me know if there is anything to change or fix, thanks!

**Comment by sabrinazimet** [comment]
thanks! looks great in terms of design. I'll review it with Louise and get back to you.
