### ISSUE TITLE
Comparison Page: Fingerprint vs ThreatMetrix

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1459]
Hi Nata :) hope you are well 

We are launching the first comparison page. This design will be used as a template for other companies comparison pages. 
There is one animation on the hero and another one on the left fixed section. I left some comments on Figma but let me know and we can discuss together.

Thank you!

Figma:
https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?type=design&node-id=4198%3A51203&mode=design&t=hb6MuoZiC47fc581-1

Source of truth: 
https://docs.google.com/document/d/1VlNCvVwttu7n8iGI9drsYX7p6SmySobRrI3cetZ73KU/edit

**Comment by sabrinazimet** [comment]
Title: “Fingerprint vs. ThreatMetrix - Compare device intelligence alternatives”

Description: “Explore an in-depth comparison between Fingerprint and ThreatMetrix. Discover why Fingerprint wins with better accuracy, faster response times, and quick implementation.”

/resources/comparisons/compare-fingerprint-vs-threatmetrix-tmx/

Put under Resources in the footer for now, and we will give it its own section when we have more in Q3 and revamp Resources

**Comment by natapg** [comment]
The path provided by @priyankasinha13 was /compare/fingerprint-vs-threatmetrix, should I change it to /resources/comparisons/compare-fingerprint-vs-threatmetrix-tmx/ ? 
What name should it has on the footer, Fingerprint vs ThreatMetrix at the end of the Resources list it ok?
Thanks!
