### ISSUE TITLE
Signal svg replacement on smart signals animation

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1475]
Heyyy! is it possible to replace the 
![Frame 2608079](https://github.com/fingerprintjs/fingerprint.com/assets/111449971/06489e21-1df5-4211-b92b-a2aee687d46e)

with a 
![jei](https://github.com/fingerprintjs/fingerprint.com/assets/111449971/5cb018a5-92c4-41a7-976c-5e3264a3559a)
(only changed the + and - signs for more clarification it is a source of energy)

mockup:
https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?type=design&node-id=3897%3A108685&mode=design&t=gHfZ8dAFpVAWAuqc-1

If it takes too much time forget it it!

**Comment by natapg** [comment]
done, deploying now!

**Comment by sabrinazimet** [comment]
amazing! thank you
