### ISSUE TITLE
Partnership webpage 

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1485]
Hi Nata, we have this new page to develop :) 

let me know everything you need I'll be here. Thanks

https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?type=design&node-id=4528%3A51546&mode=design&t=BaaymtIVzyt0DzhK-1

**Comment by sabrinazimet** [comment]
Title: Partners | Fingerprint
Description: Join Fingerprint’s partner program, to work with the world’s most accurate device identifier. Learn more and apply for the program.

Location: On footer - PARTNERS

**Comment by natapg** [comment]
Hi :) what is the path of this new page? I can't find it

**Comment by natapg** [comment]
thanks for the info! I can start working on this now
