### ISSUE TITLE
Copy changes on Github Page

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#1492]
https://docs.google.com/document/d/1pqfnuG5Tgnn9gEOboTW8LW2gGo4tpyJ1acAuO1xt8bM/edit
 
 Hi Nata, we need to get these updates on the Github page for end of week. I will be updating the mockups tomorrow probably, but I am already sending this in case you want to get some progress, i don't think you need the designs anyways!

**Comment by natapg** [comment]
Hi, sorry I'll be out the rest of the week. Please reach Bart so he can assign the changes to someone on the team!
