### ISSUE TITLE
Add Realtor logo to homepage with link to their website

### ISSUE THREAD

**Issue by skcopland** [fingerprintjs/fingerprint.com#704]
- Replace B&H logo on the homepage with realtor
- MUST include a link to their website - just make the image a link itself: https://www.realtor.com/
- @sabrina to add logo SVG to this ticket

**Comment by sabrinazimet** [comment]
https://www.figma.com/file/niHrIRowTbqQhDO7W5CPNf/Web-Mockups?node-id=3448%3A42138 

![Image](https://user-images.githubusercontent.com/111449971/186021139-dadf2572-ac16-46d5-a71f-7498efc9b08e.svg)

@natapg
