### ISSUE TITLE
Create new FAQ page

### ISSUE THREAD

**Issue by natapg** [fingerprintjs/fingerprint.com#705]
URL: [fingerprint.com/resources/frequently-asked-questions-faqs](http://fingerprint.com/resources/frequently-asked-questions-faqs)

Copy: https://docs.google.com/document/d/1wpw0ZiDN0mFSV0OUrh5jvvg2Apn2g-gWnAHkezfqtSs/edit#heading=h.ddempsgxa68xDesign: https://www.figma.com/file/niHrIRowTbqQhDO7W5CPNf/Web-Mockups?node-id=6003%3A44871

Let Sabrina and Courtney know if you have any questions on design or the copy respectively.

**Comment by sabrinazimet** [comment]
https://www.figma.com/file/niHrIRowTbqQhDO7W5CPNf/Web-Mockups?node-id=6003%3A44871 design here!
