### ISSUE TITLE
Landing Pages For Advertising

### ISSUE THREAD

**Issue by a-gwin** [fingerprintjs/fingerprint.com#719]
We want to create some landing pages for our advertising audience, that prioritize contact sales over the free signup. 

I made these quick mockups, changing the signup form for the contact sales button, as well as removing developer focused sections. [https://www.figma.com/file/X9ToimfYlrOvatB89C8ovO/Landing-Page-Mockups?node-id=0%3A1](url) 

Essentially, I just want the Homepage & Demo page copied, with the changes in the mockup, we would then want to put these on a subdomain and make them hidden from organic search. These pages would only be served to specific audiences within our advertising.

**Comment by natapg** [comment]
@a-gwin please assign it to the project Website Task and add a priority, thanks

**Comment by a-gwin** [comment]
> @a-gwin please assign it to the project Website Task and add a priority, thanks

Done.
