### ISSUE TITLE
Location Map not shown on homepage when using Brave + Private Mode with Tor

### ISSUE THREAD

**Issue by bwegrzyn** [fingerprintjs/fingerprint.com#752]
See attachment.

![image](https://user-images.githubusercontent.com/1631754/194452349-df709371-d937-46cb-a2d7-5fe29b570bda.png)

**Comment by natapg** [comment]
good catch @bwegrzyn, it makes sense because the `iplocation` can be null in some cases and we don't handle that, the question is, what should we show in such a case? I think it's something we should discuss with @Valve and the design team

**Comment by natapg** [comment]
fixed
