### ISSUE TITLE
Update Website generic components

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#810]
Hi - I am creating this task for us to update some generic components and elements of the website when we finish developing the Homepage. For example buttons, arrows, font, tags, and other components of the new UI kit. The goal is to make the pages as coherent and consistent as we can, since the new HP brings a pretty new style.

Of course that we can't change everything and there are some things that will still look a little incoherent. Taking that into consideration, we can work together to update every "updatable" component that **we know won't break the site visually.**

cc @skcopland @bwegrzyn

**Comment by natapg** [comment]
Updated Button component to match Web Design System and clean it since it was outdated
https://www.figma.com/file/mOlOAQbh5YeoamcKM15Mif/Web-Design-System---2022?type=design&t=5jp6U1TkA5AoXplD-0
PR-> https://github.com/fingerprintjs/fingerprint.com/pull/1293
