### ISSUE TITLE
New "Fingerprint Pro Product" Page

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#823]
Hey team! Just a heads up of the next page we are going to need to develop. 

This is in first phase of design, mobile view is still missing but it will be ready for next week so I wanted to tell you in advance so you can put it in your queue. 

Thanks!

prototype: https://www.figma.com/proto/Ad7wlJvqIMSOwWT5ung0Or/Website-New?page-id=8%3A2&node-id=9%3A268&viewport=181%2C714%2C0.12&scaling=scale-down-width

file: https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?node-id=9%3A268&t=RxI95PJUOXVok6uA-1

updated links. sorry, the other ones weren't available anymore.

cc @bwegrzyn @skcopland

**Comment by natapg** [comment]
thanks for the heads up. Let us know when it's ready to be developed and we'll start working, thanks.

**Comment by sabrinazimet** [comment]
This one is ready! The only pending thing is the animation on the hero; if you are going to use a video I need to polish it a little bit before sending it. Another option is to create it with CSS animation/Lottie. (this one is simpler than the one on the hp) Let me know what you think) thanks! @natapg
