### ISSUE TITLE
Github Page Updates!

### ISSUE THREAD

**Issue by sabrinazimet** [fingerprintjs/fingerprint.com#866]
- update box appearances: backgrounds, corners, strokes.
- add conversion motivators below hero button
- add new "easy to install" section below "Platform Capabilities" section

thank you ! cc @skcopland

**Comment by sabrinazimet** [comment]
Hi @natapg I see that most of the changes on the mockup are missing.
- update box general appearances: backgrounds, corners, strokes.
- add conversion motivators below hero button
- add new section "easy to install" below "Platform Capabilities" section
- adapt sections to new 12 column grid
https://www.figma.com/file/Ad7wlJvqIMSOwWT5ung0Or/Website-New?node-id=28%3A12574&t=ewVAVQxYopfOeXSj-1

**Comment by natapg** [comment]
Hi @sabrinazimet , thanks for checking. Please be more clear with the changes that are missing.

- update box general appearances: backgrounds, corners, strokes.
These changes have been made, the only thing I couldn't do is create a pseudo box like the one in Figma
![image](https://user-images.githubusercontent.com/47128448/213549543-f5b4832b-8508-4d06-a743-09fe02410c40.png)
Regarding the gradient background, as I told you before, it is not possible to have boxes with gradient backgrounds, gradient borders, and radius borders.
- add conversion motivators below hero button
if you mean this, they were already added
![image](https://user-images.githubusercontent.com/47128448/213549931-87c4eca7-2157-487f-9cf8-57f0da7e3bcb.png)
- add new section "easy to install" below "Platform Capabilities" section
![image](https://user-images.githubusercontent.com/47128448/213550180-77ef3d82-7b51-4077-a5cb-dc7431ff5aad.png)
this too.
- adapt sections to new 12 column grid
This is not part of the original ticket, but I can't find any differences with the mockup anyway. Please comment on the mockup where you see the differences. Thanks

**Comment by sabrinazimet** [comment]
Hi @natapg sorry, it was my mistake. I think my caché played me wrong and I couldn't see the updates when I reloaded the page. Now I do. Everything looks excellent!!!!!!!! Thank you and sorry again.
